### ISSUE TITLE
[Feature Request] ESP8266 support

### ISSUE THREAD

**Issue by shafr** [cp2004/OctoPrint-WS281x_LED_Status#20] opened 2020-08-20 08:27 UTC
**Is your feature request related to a problem? Please describe.**
There are a lot of great projects for ESP8266 that work with WS2812.  (TASOMOTA, ESPNOW, ...)
It is possible to communicate through MQTT with ESP, so no wirinig to RPI is required.

**Describe the solution you'd like**
It would be great if you can add mqtt communication where one would specify topic or address of device and your plugin would WLED commands there.

**Describe alternatives you've considered**
Using ESP8266 with Screen and PrinterStatus.

**Additional context**

**Comment by cp2004** [comment] 2020-08-20 11:57
Hey @shafr 
Think this is a duplicate of #10 - if your setup is different, please chime in there. I won't be able to get on to this as I don't have the hardware, but it would be a great addition. As mentioned in the other ticket, may have to be a separate plugin.

**Closed** 2020-08-20 11:57 UTC
Labels: duplicate, type: request
