### ISSUE TITLE
Hi, really enjoy this plug-in! However, I noticed when I switch the cooling progress effect from tool to bed, the effect still tracks the tool, not the bed.  Octoprint v1.5.3 (pi 3b), Marlin bugfixes2.0.x (ender 3 v2), WS281 (v0.6.0)[Bug]

### ISSUE THREAD

**Issue by vinster8108** [cp2004/OctoPrint-WS281x_LED_Status#114] opened 2021-03-01 19:33 UTC
**Steps to reproduce**

**What did you expect to happen**

**Logs and screenshots**

**Version of plugin and OctoPrint**

**(If applicable) Browser version & browser error console**

**Additional context**

**Comment by cp2004** [comment] 2021-03-01 20:33
This is a duplicate of #58 - it is fixed for the next release of the plugin, 0.7.0

**Closed by cp2004** 2021-03-01 20:33 UTC
Labels: needs review, potential bug
